### ISSUE TITLE
Alarm description for disable_or_delete_cmk is incorrect

### ISSUE THREAD

**Issue by hemanthkini** [trussworks/terraform-aws-cloudtrail-alarms#9]
The alarm description for disable_or_delete_cmk is copied from another alarm (console_signin_failures). It may be worth replacing with something like this?

Monitoring attempts to disable or delete Customer Master Keys (CMKs) may detect an attempt to delete or invalidate customer production data stored on AWS.

**Comment by jsclarridge** [comment]
@hemanthkini Thank you for pointing this out and apologies for the long delay. https://github.com/trussworks/terraform-aws-cloudtrail-alarms/pull/12 (v2.0.2) updated the alarm description.
